# Ficheiro de configuração da Netlify

[build]
  # O comando para construir o site
  command = "npm run build"
  # A pasta onde o resultado do build é colocado
  publish = "dist"

[functions]
  # A pasta onde estão as suas funções de backend
  directory = "netlify/functions/"