# Ficheiro de configuração da Netlify

[build]
  # O comando para construir o site
  command = "npm run build"
  # A pasta onde o resultado do build é colocado
  publish = "dist"
  # A pasta onde estão as suas funções de backend
  functions = "netlify/functions/"

[build.environment]
  # A sintaxe correta para dizer ao scanner para ignorar a chave do Google Analytics
  SECRETS_SCAN_OMIT_KEYS = '["VITE_GA_MEASUREMENT_ID"]'