# netlify.toml
[functions]
  directory = "netlify/functions/"

[build]
  # Diz ao scanner de segredos para ignorar esta chave específica
  environment = { SECRETS_SCAN_OMIT_KEYS = ["VITE_GA_MEASUREMENT_ID"] }